name: CI/CD
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
      redis:
        image: redis
        ports: ["6379:6379"]
        options: --entrypoint redis-server
      chrome:
        image: selenium/standalone-chrome:3.141.59-zirconium # this version should match that of the selenium-webdriver gem
        env:
          HUB_URL: http://chrome:4444/wd/hub
        volumes:
          - /dev/shm:/dev/shm

    steps:
      - uses: actions/checkout@v1
      - uses: nanasess/setup-chromedriver@master
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Build and run test
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake webpacker:install
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rake db:seed
          bundle exec rspec .